### ISSUE TITLE
Tvnow Plugin crasht beim Starten

### ISSUE THREAD

**Issue by AnneWielis** [Pati/plugin.video.tvnow.de#11]
Habe das Plugin ein paar Monate nicht benutzt. Es läuft Kodi 19, Version ist 0,5,24. 

2021-05-27 22:36:11.912 T:1466     INFO <general>: CPythonInvoker(2, /home/anne/.kodi/addons/plugin.video.tvnow.de/service.py): script successfully run
```
2021-05-27 22:36:11.971 T:1466     INFO <general>: Python interpreter interrupted by user
2021-05-27 22:36:12.210 T:1252  WARNING <general>: CGUIMediaWindow::OnMessage - updating in progress
2021-05-27 22:36:36.267 T:3758     INFO <general>: CAddonMgr::FindAddon: plugin.video.tvnow.de v0.5.24+matrix.0 installed
2021-05-27 22:36:36.274 T:3856     INFO <general>: initializing python engine.
2021-05-27 22:36:36.383 T:1252  WARNING <general>: CGUIMediaWindow::OnMessage - updating in progress
2021-05-27 22:36:48.929 T:1252    ERROR <general>: Control 55 in window 10025 has been asked to focus, but it can't
2021-05-27 22:36:48.953 T:3925     INFO <general>: initializing python engine.
2021-05-27 22:36:50.565 T:3925  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-05-27 22:36:50.847 T:3925    ERROR <general>: Skipped 1 duplicate messages..
2021-05-27 22:36:50.847 T:3925    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'simplejson.errors.JSONDecodeError'>
                                                   Error Contents: Expecting value: line 1 column 1 (char 0)
                                                   Traceback (most recent call last):
                                                     File "/home/anne/.kodi/addons/plugin.video.tvnow.de/addon.py", line 72, in <module>
                                                       nav.rootDir()
                                                     File "/home/anne/.kodi/addons/plugin.video.tvnow.de/resources/lib/navigation.py", line 264, in rootDir
                                                       recommendations = tvNow.getRecommendationsList()
                                                     File "/home/anne/.kodi/addons/plugin.video.tvnow.de/resources/lib/tvnow.py", line 187, in getRecommendationsList
                                                       data = r.json()
                                                     File "/home/anne/.kodi/addons/script.module.requests/lib/requests/models.py", line 900, in json
                                                       return complexjson.loads(self.text, **kwargs)
                                                     File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
                                                       return _default_decoder.decode(s)
                                                     File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
                                                       obj, end = self.raw_decode(s)
                                                     File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
                                                       return self.scan_once(s, idx=_w(s, idx).end())
                                                   simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
                                                   -->End of Python script error report<--
```

Ist das ein Bug oder eher ein Bedienfehler?

**Comment by Pati** [comment]
Eventuell hilft es sich nocheinmal im Addon neu anzumelden.
