### ISSUE TITLE
TvNow Fehler bei Wiedergabe aus RTL oder VOX

### ISSUE THREAD

**Issue by cbecker2** [Pati/plugin.video.tvnow.de#14]
Hallo,

hier meine zugegebenermaßen leider nicht ganz aktuelle Konfiguration:
-Hardware: Raspberrypi 3b, BCM2835 Revision a02082, CPU ARMv7 rev4 (v71)
-Kodi 18.9.0 Leia
-TvNow Plugin 0.5.30

Seit 11.10.2023 bekomme ich einen Fehler, wenn ich z.B. etwas von RTL (z.B. RTL Aktuell) oder von VOX (z.B. Die Höhle der Löwen) abspielen will. Bis dahin hat das eigentlich immer problemlos funktioniert. 

Ich habe im Kodi das Logging aktiviert, der nachfolgend aufgeführte Auszug kam beim Start einer Sendung über TvNow.

`2023-10-12 16:56:42.071 T:1860170624   DEBUG: LIRC: - NEW 160 0 KEY_OK devinput (KEY_OK)
2023-10-12 16:56:42.096 T:1937530944   DEBUG: HandleKey: 11 (0x0b, obc244) pressed, action is Select
2023-10-12 16:56:42.121 T:1937530944   DEBUG: OnPlayMedia plugin://plugin.video.tvnow.de/?action=playVod&vod_url=6077923
2023-10-12 16:56:42.128 T:1937530944   DEBUG: StartScript - calling plugin TvNow('plugin://plugin.video.tvnow.de/','21','?action=playVod&vod_url=6077923','resume:fal                        se')
2023-10-12 16:56:42.128 T:1463808896   DEBUG: Thread LanguageInvoker start, auto delete: false
2023-10-12 16:56:42.128 T:1463808896    INFO: initializing python engine.
2023-10-12 16:56:42.129 T:1463808896   DEBUG: CPythonInvoker(37, /storage/.kodi/addons/plugin.video.tvnow.de/default.py): start processing
2023-10-12 16:56:42.149 T:1807721344   DEBUG: Thread scriptobs start, auto delete: false
2023-10-12 16:56:42.178 T:1463808896   DEBUG: -->Python Interpreter Initialized<--
2023-10-12 16:56:42.178 T:1463808896   DEBUG: CPythonInvoker(37, /storage/.kodi/addons/plugin.video.tvnow.de/default.py): the source file to load is "/storage/.kodi/                        addons/plugin.video.tvnow.de/default.py"
2023-10-12 16:56:42.180 T:1463808896   DEBUG: CPythonInvoker(37, /storage/.kodi/addons/plugin.video.tvnow.de/default.py): setting the Python path to /storage/.kodi/a                        ddons/plugin.video.tvnow.de:/storage/.kodi/addons/script.module.certifi/lib:/storage/.kodi/addons/script.module.chardet/lib:/storage/.kodi/addons/script.module.idna/                        lib:/storage/.kodi/addons/script.module.inputstreamhelper/lib:/storage/.kodi/addons/script.module.pysocks/lib:/storage/.kodi/addons/script.module.requests/lib:/stora                        ge/.kodi/addons/script.module.routing/lib:/storage/.kodi/addons/script.module.urllib3/lib:/usr/share/kodi/addons/script.module.pycryptodome/lib:/usr/lib/python27.zip                        :/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packag                        es:/usr/lib/python2.7/site-packages/gtk-2.0
2023-10-12 16:56:42.180 T:1463808896   DEBUG: CPythonInvoker(37, /storage/.kodi/addons/plugin.video.tvnow.de/default.py): entering source directory /storage/.kodi/ad                        dons/plugin.video.tvnow.de
2023-10-12 16:56:42.181 T:1463808896   DEBUG: CPythonInvoker(37, /storage/.kodi/addons/plugin.video.tvnow.de/default.py): instantiating addon using automatically obt                        ained id of "plugin.video.tvnow.de" dependent on version 2.26.0 of the xbmc.python api
2023-10-12 16:56:42.349 T:1937530944   DEBUG: ------ Window Init (DialogBusy.xml) ------
2023-10-12 16:56:43.890 T:1463808896   DEBUG: CAddonSettings[plugin.video.tvnow.de]: loading setting definitions
2023-10-12 16:56:43.890 T:1463808896   DEBUG: CAddonSettings[plugin.video.tvnow.de]: trying to load setting definitions from old format...
2023-10-12 16:56:43.892 T:1463808896   DEBUG: CAddonSettings[plugin.video.tvnow.de]: loading setting values
2023-10-12 16:56:43.904 T:1463808896   DEBUG: CAddonSettings[plugin.video.tvnow.de]: loading setting definitions
2023-10-12 16:56:43.905 T:1463808896   DEBUG: CAddonSettings[plugin.video.tvnow.de]: trying to load setting definitions from old format...
2023-10-12 16:56:43.906 T:1463808896   DEBUG: CAddonSettings[plugin.video.tvnow.de]: loading setting values
2023-10-12 16:56:43.907 T:1463808896   DEBUG: CSettingsManager: requested setting (password) was not found.
2023-10-12 16:56:44.674 T:1463808896   DEBUG: CAddonSettings[plugin.video.tvnow.de]: loading setting definitions
2023-10-12 16:56:44.674 T:1463808896   DEBUG: CAddonSettings[plugin.video.tvnow.de]: trying to load setting definitions from old format...
2023-10-12 16:56:44.676 T:1463808896   DEBUG: CAddonSettings[plugin.video.tvnow.de]: loading setting values
2023-10-12 16:56:44.680 T:1463808896   DEBUG: CAddonSettings[plugin.video.tvnow.de]: loading setting definitions
2023-10-12 16:56:44.680 T:1463808896   DEBUG: CAddonSettings[plugin.video.tvnow.de]: trying to load setting definitions from old format...
2023-10-12 16:56:44.683 T:1463808896   DEBUG: CAddonSettings[plugin.video.tvnow.de]: loading setting values
2023-10-12 16:56:44.686 T:1463808896   DEBUG: CAddonSettings[plugin.video.tvnow.de]: loading setting definitions
2023-10-12 16:56:44.686 T:1463808896   DEBUG: CAddonSettings[plugin.video.tvnow.de]: trying to load setting definitions from old format...
2023-10-12 16:56:44.688 T:1463808896   DEBUG: CAddonSettings[plugin.video.tvnow.de]: loading setting values
2023-10-12 16:56:44.893 T:1463808896   ERROR: Login Error: {"status":404,"message":"Route not Found","routeExists":false}
2023-10-12 16:56:44.895 T:1463808896   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'drmProtected' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.tvnow.de/default.py", line 41, in <module>
                                                vod.playAsset(params['vod_url'])
                                              File "/storage/.kodi/addons/plugin.video.tvnow.de/resources/lib/vod.py", line 9, in playAsset
                                                tvnow.play(asset_id)
                                              File "/storage/.kodi/addons/plugin.video.tvnow.de/tvnow.py", line 267, in play
                                                playBackUrl, drmProtected, drmURL = self.getPlayBackUrl(assetID, loggedIn, live)
                                              File "/storage/.kodi/addons/plugin.video.tvnow.de/tvnow.py", line 261, in getPlayBackUrl
                                                return "", drmProtected, ""
                                            UnboundLocalError: local variable 'drmProtected' referenced before assignment
                                            -->End of Python script error report<--
2023-10-12 16:56:44.895 T:1463808896   DEBUG: onExecutionDone(37, /storage/.kodi/addons/plugin.video.tvnow.de/default.py)
2023-10-12 16:56:44.915 T:1937530944   DEBUG: ------ Window Init (DialogNotification.xml) ------
2023-10-12 16:56:45.187 T:1463808896    INFO: Python interpreter stopped
2023-10-12 16:56:45.187 T:1463808896   DEBUG: Thread LanguageInvoker 1463808896 terminating
2023-10-12 16:56:45.203 T:1807721344   DEBUG: Thread scriptobs 1807721344 terminating
2023-10-12 16:56:45.203 T:1937530944   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
2023-10-12 16:56:45.204 T:1937530944   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.tvnow.de/?action=playVod&vod_url=6077923]
2023-10-12 16:56:45.204 T:1937530944   DEBUG: Playlist Player: one or more items failed to play... aborting playback
2023-10-12 16:56:45.204 T:1937530944   DEBUG: ------ Window Init (DialogConfirm.xml) ------
`

Ich habe heute mal testweise die neueste Kodi-Version auf einer anderen Speicherkarte installiert, danach TvNow Plugin installiert, aber bekomme den gleichen Fehler. Sieht mir nach irgendwas mit Python aus.

Grüße
Christian

**Comment by cbecker2** [comment]
Hier die Debug-Daten als Datei - ist dann evtl. besser lesbar....
[Kodi TvNow Debug.txt](https://github.com/Pati/plugin.video.tvnow.de/files/12884361/Kodi.TvNow.Debug.txt)

**Comment by hasifantasy** [comment]
Gleiches Problem bei mir unter aktuellem OSMC und Raspberry Pi 4.

**Comment by hasifantasy** [comment]
Ergänzend die Fehlermeldung aus dem Kodi (Version 20.2) Log unter osmc 2023.08-1:

2023-10-19 18:45:58.736 T:23502   error <general>: Login Error: {"status":404,"message":"Route not Found","routeExists":false}
2023-10-19 18:45:58.739 T:23502   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'UnboundLocalError'>
                                                   Error Contents: local variable 'drmProtected' referenced before assignment
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.video.tvnow.de/addon.py", line 42, in <module>
                                                       vod.playAsset(params['vod_url'])
                                                     File "/home/osmc/.kodi/addons/plugin.video.tvnow.de/resources/lib/vod.py", line 6, in playAsset
                                                       tvnow.play(asset_id)
                                                     File "/home/osmc/.kodi/addons/plugin.video.tvnow.de/resources/lib/tvnow.py", line 282, in play
                                                       playBackUrl, drmProtected, drmURL = self.getPlayBackUrl(
                                                     File "/home/osmc/.kodi/addons/plugin.video.tvnow.de/resources/lib/tvnow.py", line 276, in getPlayBackUrl
                                                       return "", drmProtected, ""
                                                   UnboundLocalError: local variable 'drmProtected' referenced before assignment
                                                   -->End of Python script error report<--

**Comment by lichtraum** [comment]
Gleiches Problem bei mir. Umgebung ist: Android TV mit Kodi 20.2.0

**Comment by cbecker2** [comment]
Ich habe mein LibreElec / Kodi neu installiert und bin jetzt auf LibreElec 11.0.3 mit Kodi 20.2. In dem kodinerds addon 7.0.1.4 steht dann Tvnow 0.6.1+matrix.0 zur Verfügung. Aber hierzu müssen noch einige Abhängigkeiten mit installiert werden. Nähere Infos hatte ich hier gefunden:
https://www.kodinerds.net/thread/57646-release-tvnow-rtl-watchbox-vox-ntv-nowus-rtl2-nitro/?postID=731152#post731152
Ab da einfach mal lesen, ist nicht ganz so viel. Bei mir funktioniert das Tvnow addon jetzt wieder, wenn auch langsam und mit ein paar Änderungen in der Bedienung.

**Comment by lichtraum** [comment]
Danke für den Hinweis.
Wenn man das Sandmann79’s repository https://github.com/Sandmann79/xbmc/tree/master als ZIP Addon Repository installiert, funktioniert das Update von TV Now und damit dann auch wieder der Stream.

**Comment by cbecker2** [comment]
Da zumindest _mein_ Anliegen gelöst ist, glaube ich, ich mache hier mal zu. **Danke** @lichtraum für Deinen Hinweis dass es bei Dir auch funktioniert!
