### ISSUE TITLE
No module named Cryptodome.Cipher

### ISSUE THREAD

**Issue by pejobo** [Pati/plugin.video.tvnow.de#4]
Seit Januar bekomme ich diesen Fehler:

```
2020-02-22 20:25:22.785 T:1764888896   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named Cryptodome.Cipher
                                            Traceback (most recent call last):
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.tvnow.de/service.py", line 10, in <module>
                                                import resources.lib.manifestServer as manifestServer
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.tvnow.de/resources/lib/manifestServer.py", line 14, in <module>
                                                import tvnow
                                              File "/var/lib/kodi/.kodi/addons/plugin.video.tvnow.de/tvnow.py", line 16, in <module>
                                                from Cryptodome.Cipher import DES3
                                            ImportError: No module named Cryptodome.Cipher
                                            -->End of Python script error report<--
```

System information:
```
2020-02-22 20:22:37.879 T:1903982880  NOTICE: Starting Kodi (18.4 Git:20190901-nogitfound). Platform: Linux ARM 32-bit
2020-02-22 20:22:37.879 T:1903982880  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
2020-02-22 20:22:37.880 T:1903982880  NOTICE: Kodi compiled 2019-09-01 by GCC 8.3.0 for Linux ARM 32-bit version 5.1.0 (327936)
2020-02-22 20:22:37.880 T:1903982880  NOTICE: Running on Arch Linux ARM rolling, kernel: Linux ARM 32-bit version 4.19.80-2-ARCH
2020-02-22 20:22:37.880 T:1903982880  NOTICE: FFmpeg version/source: 4.0.4-Kodi
2020-02-22 20:22:37.880 T:1903982880  NOTICE: Host CPU: ARMv7 Processor rev 5 (v7l), 4 cores available
2020-02-22 20:22:37.880 T:1903982880  NOTICE: ARM Features: Neon enabled
```

Siehe auch #3

**Comment by Pati** [comment]
Das Problem liegt bei ArchLinux und nicht an meinem Plugin: https://bugs.archlinux.org/task/63439

**Comment by pejobo** [comment]
Hm, den Link hatte ich auch gesehen. Zitat: But this is *WRONG* for Kodi. Kodi has an officially exported interface for plugins and guarantees that the "Crypto" module is available (and that's why it is a dependency of our package). Any Kodi add-on that expects the Cryptodome module, like the Netflix addon you linked, is violating the Kodi development guidelines.

Mit der Abhängigkeit zum Modul Crypto in der Version vor Januar hatte es ja auch funktioniert.

**Comment by Pati** [comment]
Im Januar hatte ich noch pydes verwendet, welches aber nur im Kodinerds Repository liegt. Cryptodome ist Bestandteil von Kodi, weshalb ich dorthin gewechselt bin. Ich habe nie die Version mit Crypto verwendet. Das Netflix Addon verwndet übrigens auch Cryptodome.

Aber zurück zu deinem Problem. In ArchLinux war für das Kodi Paket eine falsche Abhängigkeit eingepflegt, wodurch Cryptodome mit dem namespace Crypto installiert wurde. (siehe auch restliche Kommentare unter dem Link)

**Comment by pejobo** [comment]
Hi Pati, 

ich versuche gerade rauszufinden, ob ich das für meine Installation fixen kann. Anscheinend ist der Fix aus dem von dir verlinktem Bugreport nicht in dem arm-Port für den Raspberry gelandet :/ (1). 
Kennst du dich damit aus? Mir scheint es so, als müsste ich das Paket lokal bauen. Würde ich gerne vermeiden, weil ich keine cross compile Umgebung habe.
Parallel habe ich mich auch an einem PR für das Paket `kodi-rbp` versucht (2).


(1) https://github.com/archlinuxarm/PKGBUILDs/blob/master/alarm/kodi-rbp/PKGBUILD
(2) https://github.com/archlinuxarm/PKGBUILDs/pull/1784

**Comment by pejobo** [comment]
Der PR wurde gemerged, damit funktioniert es jetzt bei mir!
