### ISSUE TITLE
Addon bricht beim Start mit Fehler ab

### ISSUE THREAD

**Issue by t0mcat1337** [Pati/plugin.video.tvnow.de#7]
Wenn das Addon in Kodi gestartet wird, bricht es sofort mit Fehler ab.

Das ist im Kodi Log:

```
2020-06-22 10:59:56.699 T:139682436331264   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: string indices must be integers
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.tvnow.de/default.py", line 33, in <module>
                                                if db.updateDatabase():
                                              File "/storage/.kodi/addons/plugin.video.tvnow.de/database.py", line 30, in updateDatabase
                                                for item in listItem["formats"]:
                                            TypeError: string indices must be integers
                                            -->End of Python script error report<--
```

**Comment by Pati** [comment]
Danke für die Rückmeldung, in der neusten Version sollte es wieder gehen

**Comment by IVleafclover** [comment]
Vielen Dank für den schnellen Fix.
Fehlt hier noch ein Update des Pati Repos? Über dieses finde ich aktuell nur die Version 0.5.11.
Oder sollte ich das Add On anders installieren? Quasi direkt über die Zip?

**Comment by Pati** [comment]
@IVleafclover Am besten über das Kodinerds repo: https://repo.kodinerds.net/
